language: nix
nix: 2.3.1
env:
  global:
  - secure: iaFtvrhDVdNNXFYjcN1bYViNnfW1/Umpg+ajGoN1rKVcrX4c9EXhaaT3/T1HtpL+f3QJfxwABJo5vOveMGsvEcVK36fgwoDdP3IofIdffH10IguozN44O01AUwLwvi5dx8IUT+ArOSY0jPP0YoBm3jgTpbWrlhxWcE/XphlPHarPouvXznTijUyCgSTCOneJFRweiD+LXB9tegtpbx/ehQhdH2DPc27yNEcGMX8A7FQp+Qyuna4wokJgUAe69zssR/WMJoHmU6FyQyix2Ht8fjCjNWhVltwFvNIancKH/O7OH6ObdpQiI14LE/7y0TsOLJPUYT5CqAUwONkfCyCEou6is1nH7R6FdcxAdDUe2W5wlnceWeTK+5f5GW3lloiRfhYFT8kK8hTSTx56v4wyxoqBA/stviw1e9RRiB0YYprRf35opgeOnYYhxDbMZlCEO3rHgsg6tWmGrtLuf9IeXT82/y1O04DNvrLJKUVDwy0Z4ygmZ7z4DYSj2X4WpksBUZDojHDFYrmHgYx5yQLs4+e1T9GZooO4gglOmViW4t5riGmvgQyhKweoiX421hx56SUaRfekNzMgjDOeKOV+C0Vg5SnzUJ8MSo+EHPAXpLU7WAiGtE4bK+NqPC3DeyKE8GAiwBe8wrA9xwxEtipC177yJujqRaM/3lp7Ka2QHaM=
  - secure: S9r2BL2x1G0MRTiz8adAyAQPj7FNUtgu4M6esyVpnuGHYg6D81QfDVAIqF+jR+lTmUfmAkvr1m6QZ6xJ29IdwU9e9BkTbI1cSusybalrTKLm32taWn2gfCoM3hcN9iMiVUC9GXQtkMcUn4/R5TEq5qrzCtP0AbJOd4sMSbzQ+IC9y4E31TwMLbkLZ4iNcceKNArqskCku3cNhro4cmmBc/BTLvg0t84rvmjJjEO/QwqADGXQ6xOZ41is12tshbgvUwknw0GQioid/rlarMhosxwK8lwPA7h/VGO443RaIuFmnp8s1moToNYdrQSneI51vCfFdyXV9nEXjstK4nkp4fHGaQ52/lAc6Z9waAx7xp3S3PaWTmy9yWZPd/e9EdCfhsY7lXzB0snUiXUk/d8wOGjNMoFhkTd9GJtPdlYNodZY51CLMd6qVpkRkUXQrwk5JQ4Q/8W+ekKFRsPiBvXITNMqq6Rf3JbS59aaatWa/QgKb3T/AAsKfCFOXLwFZeJWKV0y90xJN7sRyGlvu1/HY09l/+Ey0aOUCceRK2tdLQeA+WZnZwSBKwRSjOQjpQWrK+CrNBcFnHFlXXl9xL7ELgowx6x8LioMSEsYaFF62uDRXvT2mivAgw7h4eX0BPQ8nflqez2m4BiN3o7T3b+uWDChjq7f8ZR1pp7KkqSb6zM=
  - secure: GzO+P8SXZFS7llMAqFu9QSf78dkLVce5HYkVsWu+Ey38se69EiFGEkxNXfhuNDCcjwDEBl7tyQqDPWCSoMb0QENmdaFbDrI8iZ2GGP/vkQPNnak060fgGNKjoyNfjsXKJzI83gJ4QhBgYa41wOTeB3SzBIZaMBxCshKEPFVjq2m45RnZOk4D08x74XP/FZKHeAqDR+jzm/Yj2qTyR0QYaTk5cIH5UkyM79NLlXFsDQNJ9lL+po7EHQzErfm83BDsWuwYQPs4yVdY+y5MJtZtvrklf3UB7EdpAORQWW/xCSv1kwYfnh6YaO7xA6JESEtKu8z5ayunoeSWy6o47Pr52/D7SsLMqtiJvz45kI+Teg8Zr4u5VAmMxNaOMSwrM0SwsaReGLu1ZPBACYoqOaLRGIH4JT2B+5mtAwB+PpHHNAsPvB5BRF66ixAm7cJK3Ol/BTzfUovBkTz+49t+XKse2x8nhYthO1LjnuQsWBNrNuUE+8XaAvpxn5P3WzWLHFVFRGjWJlk0oWDlaDIdUSorOWhJLcS8qkaKrzwcjqq9GEvajB+6HomnFb2ca7jPRhsJNQGAQcliQ/0grJTkoLOB5eqWeLE0o4YVCEhU10uY7eI4eQNC/Vt8dF+MI2qaxwQwc0vI+bkWqhHb0QPXMVJL9eKFXgpFoUYyUcbNXZ8mxdc=
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
install: true
before_install:
  - nix-channel --add https://nixos.org/channels/nixos-19.09 nixos
  - nix-channel --update
  - nix-channel --list
  - . /home/travis/.nix-profile/etc/profile.d/nix.sh
  -
script:
- "./travis-ci.sh"
