= graphs

An easy to use java api for graphs which currently supports simple graphs and event streaming. The graph api follows
a few principles which keeps things simple for the user:

* a graph is always valid
* referencing missing elements will create them
* for event graphs, creating and changing a graph, vertices, or edges will result in an event
* never return null

image:https://travis-ci.org/moaxcp/graphs.svg?branch=master["Build Status", link="https://travis-ci.org/moaxcp/graphs"]
image:https://sonarcloud.io/api/project_badges/measure?project=com.github.moaxcp%3Agraphs&metric=alert_status["Quality Gate", link="https://sonarcloud.io/dashboard?id=com.github.moaxcp%3Agraphs"]
image:https://sonarcloud.io/api/project_badges/measure?project=com.github.moaxcp:graphs&metric=coverage["Coverage", link="https://sonarcloud.io/dashboard?id=com.github.moaxcp%3Agraphs"]
image:https://sonarcloud.io/api/project_badges/measure?project=com.github.moaxcp:graphs&metric=duplicated_lines_density["Duplication", link="https://sonarcloud.io/dashboard?id=com.github.moaxcp%3Agraphs"]

= Definitions and concepts

== Graph
* consists of vertices and edges
* May be directed or undirected
* edges must always connect vertices
* undirected may only have one edge between any two vertices
* directed may only have one edge in each direction between any two vertices
* may have an 'id'
* has properties
* has properties inherited by all vertices
* has properties inherited by all edges

== EventGraph
* sends events to the EventBus when modified

== Elements
* vertices and edges of parent graph
* inherit properties from parent graph
* has local properties
* local properties override inherited properties

== Vertex
* must have 'id' property
* id must be unique for all vertices in graph

== Edge
* must have 'from' and 'to' properties
* 'from' and 'to' connect two vertices by id
* may have an 'id'

= API

== Graph

Graph can be undirected or directed. An undirected graph can have only one edge between any two vertices. A
directed graph can have two edges between any two vertices but they must be in opposite directions.

----
Graph undirected = new UnidrectedGraph();
Graph directed = new DirectedGraph();
Graph undirectedEvent = new UnidrectedEventGraph();
Graph directedEvent = new DirectedEventGraph();
----

There are three main interfaces: Graph, Edge, and Vertex. Edge and Vertex are inner-classes of Graph.

== Vertices and Edges

vertex() and edge() methods provide an api for creating or finding elements of the graph. If an element already exists
it is returned.

----
graph.vertex("A");
graph.vertex("B");
graph.edge("A", "B");
----

It is not necessary to create vertices before creating an edge. One statement will create the same graph.

----
graph.edge("A", "B");
----

Elements are returned which allows method chaining. The same graph can be created using `connectsTo`.

----
graph.vertex("A").connectsTo("B");
----

The Vertex and Edge classes have other convenience methods for building a graph.

= Building a Graph

----
Graph graph = new DirectedGraph();
graph.vertex("A")
    .connectsTo("E")
    .toVertex("B") //returns B
    .toVertex("C") //returns C
    .fromVertex("D") //returns D
    .connectsTo("B")
    .connectsTo("E")
    .connectsTo("A")
    .connectsFrom("A")
    .fromVertex("G") //returns G
    .connectsFrom("F")
----

== properties

A property must have a name and value. The name and value cannot be null. Graph, Vertex, and Edge can have properties.

----
graph.property("name", "graph");
graph.vertex("A").property("name", "A");
graph.edge("A", "B").property("distance", 10);
----

=== inherited properties

Graph contains properties for all edges and all vertices to inherit. Common properties only need to be set once
in the graph rather than in each individual element. Local properties set on an Edge or Vertex override properties set
in the graph.

----
graph.edgeProperty("color", "blue");
graph.vertexProperty("color", "green");

graph.vertex("A").property("color", "red");
graph.edge("A", "B").property("yellow");
graph.edge("A", "C");
----

=== id

`id` can be any object which correctly implements equals and hashCode. Most of the examples use String but Integer or
even UUID could be used.

Vertex requires an `id`. `id` must always exist but it can be changed at any time.

```
graph.vertex("A");
```

Creates a vertex with id of "A".

```
graph.vertex("A").id("B");
```

Creates a vertex with id of "A" and changes it to "B".

Graph and Edge have an optional `id`. The `id` in Graph and Edge can be changed or removed at any time.

=== `from` and `to`

Edge requires `from` and `to`. These properties identify the two vertices the edge connects. `from` and `to`
must always exist but they can be changed to connect different vertices.

