= graphs

An easy to use java api for graphs which currently supports simple graphs and event streaming. The graph api follows
a few principles which keeps things simple for the user:

* a graph is always valid
* referencing missing elements will create them
* for event graphs, creating and changing a graph, vertices, or edges will result in an event
* never return null

image:https://travis-ci.org/moaxcp/graphs.svg?branch=master["Build Status", link="https://travis-ci.org/moaxcp/graphs"]
image:https://sonarcloud.io/api/project_badges/measure?project=com.github.moaxcp.graphs%3Agraphs&metric=alert_status["Quality Gate", link="https://sonarcloud.io/dashboard?id=com.github.moaxcp.graphs%3Agraphs"]
image:https://img.shields.io/maven-central/v/com.github.moaxcp/graphs.svg["Maven Central", link="https://mvnrepository.com/artifact/com.github.moaxcp/graphs"]
image:https://www.javadoc.io/badge/com.github.moaxcp/graphs.svg["Javadocs", link="https://www.javadoc.io/doc/com.github.moaxcp/graphs"]

= Definitions and concepts

== Graph

* consists of vertices and edges
* May be directed or undirected
* edges must always connect vertices
* undirected may only have one edge between any two vertices
* directed may only have one edge in each direction between any two vertices
* may have an 'id'
* has properties
* has properties inherited by all vertices
* has properties inherited by all edges

== EventGraph
* sends events to the EventBus when modified

== Elements
* vertices and edges of parent graph
* inherit properties from parent graph
* has local properties
* local properties override inherited properties

== Vertex
* must have 'id' property
* id must be unique for all vertices in graph

== Edge
* must have 'from' and 'to' properties
* 'from' and 'to' connect two vertices by id
* may have an 'id'

= API

== Graph

Graph can be undirected or directed. An undirected graph can have only one edge between any two vertices. A
directed graph can have two edges between any two vertices but they must be in opposite directions.

----
Graph undirected = new UnidrectedGraph();
Graph directed = new DirectedGraph();
Graph undirectedEvent = new UnidrectedEventGraph(EventBus.getDefault());
Graph directedEvent = new DirectedEventGraph(EventBus.getDefault());
----

There are three main interfaces: Graph, Edge, and Vertex. Edge and Vertex are inner-classes of Graph.

== Vertices and Edges

vertex() and edge() methods provide an api for creating or finding elements of the graph. If an element already exists
it is returned.

----
graph.vertex("A");
graph.vertex("B");
graph.edge("A", "B");
----

It is not necessary to create vertices before creating an edge. One statement will create the same graph.

----
graph.edge("A", "B");
----

Elements are returned which allows method chaining. The same graph can be created using `connectsTo`.

----
graph.vertex("A").connectsTo("B");
----

The Vertex and Edge classes have other convenience methods for building a graph.

== properties

A property must have a name and value. The name and value cannot be null. Graph, Vertex, and Edge can have properties.

----
graph.property("name", "graph");
graph.vertex("A").property("name", "A");
graph.edge("A", "B").property("distance", 10);
----

=== inherited properties

Graph contains properties for all edges and all vertices to inherit. Common properties only need to be set once
in the graph rather than in each individual element. Local properties set on an Edge or Vertex override properties set
in the graph.

----
graph.edgeProperty("color", "blue");
graph.vertexProperty("color", "green");

graph.vertex("A").property("color", "red");
graph.edge("A", "B").property("yellow");
graph.edge("A", "C");
----

=== id

`id` can be any object which correctly implements equals and hashCode. Most of the examples use String but Integer or
even UUID could be used.

Vertex requires an `id`. `id` must always exist but it can be changed at any time.

```
graph.vertex("A");
```

Creates a vertex with id of "A".

```
graph.vertex("A").id("B");
```

Creates a vertex with id of "A" and changes it to "B".

Graph and Edge have an optional `id`. The `id` in Graph and Edge can be changed or removed at any time.

=== `from` and `to`

Edge requires `from` and `to`. These properties identify the two vertices the edge connects. `from` and `to`
must always exist but they can be changed to connect different vertices.

== Event Graphs

Event graphs post to an EventBus after a change has been made to the graph.

----
Graph graph = new DirectedEventGraph(EventBus.getDefault());
graph.edge("A", "B");
----

The above code will send 4 events to the bus in order: DirectedGraphCreated, VertexCreated, VertexCreated, EdgeCreated.
A subscriber to these events can create a view of the graph as it is modified.

= Releases

== 0.4.0

Splitting projects into core, greenrobot, graphviz, and truth. Added support for java modules.

== 0.3.0

Added initial support for graphviz. Added getProperties(), getEdgeProperties(), and getVertexProperties() to Graph api.
Removing edgeTo(), edgeFrom(), vertexTo(), and vertexFrom() methods in Vertex to reduce complexity of api.

== 0.2.0

Javadoc for `Vertex.setId` has been updated to throw IllegalArgumentException of a vertex with id already exists. This
case is also now tested. `getBus` and generic type `BUS` has been removed from EventGraph. Fixed bug #22 where setting
`from` or `to` on an edge does not result in an event.

== 0.1.1

This release fixes a major issue where changing a vertex id resulted in adjacentEdges, inEdges, and outEdges being
inaccurate. A check was also added to `Vertex.setId` which throws IllegalArgumentException if a vertex with id already
exists.

== 0.1.0

This release includes the main Graph interface and implementations for undirected and directed graphs. There are also
event graph implementations which post to greenrobot's event bus. The events are immutable and may be used to track
changes in the graph by visualizations and other tools. Some edge methods have been benchmarked using jmh and optimized
for performance.

= License

The license can be found in the LICENSE file.

MIT License

Copyright (c) 2019 John Mercier