name: Nix Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v6
    - name: Setup nixos-19.09 channel
      run:  |
        nix-channel --add https://nixos.org/channels/nixos-19.09 nixos
        nix-channel --update
        nix-channel --list
    - name: Install Adopt Open JDK
      run: nix-env -iA nixos.adoptopenjdk-bin
    - name: Install Graphviz
      run: nix-env -iA nixos.graphviz
    - name: Run nix build script
      run: ./gradlew build
