name: Nix Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v6
    - name: list channels
      run: nix-channel --list
    - name: Install Adopt Open JDK
      run: nix-env -iA nixos.adoptopenjdk-bin
    - name: Install Graphviz
      run: nix-env -iA nixos.graphviz
    - name: Run nix build script
      run: ./gradlew build
